oficialia_homepage:
    path:     /
    defaults: { _controller: OficialiaBundle:Default:index }
documento:
    path:   /agregar-documento
    defaults: {_controller: OficialiaBundle:Documento:documento}
guardar_documento:
    path:   /guardar-documento
    defaults: {_controller: OficialiaBundle:Documento:guardar}
documentos_get:
    path:   /ver-documentos
    defaults: {_controller: OficialiaBundle:Documento:getDocumentos}
cargando:
    path:   /cargando
    defaults: {_controller: OficialiaBundle:Default:cargando}
documento_departamento:
    path:   /documento-departamento
    defaults: {_controller: OficialiaBundle:Documento:departamento}
documento_instruccion:
    path:   /documento-instruccion
    defaults: {_controller: OficialiaBundle:Documento:instruccion}
documento_institucion:
    path:   /documento-institucion
    defaults: {_controller: OficialiaBundle:Documento:institucion}
documento_formato:
    path:   /documento-formato
    defaults: {_controller: OficialiaBundle:Documento:formato}
documento_tipodocumento:
    path:   /documento-tipo
    defaults: {_controller: OficialiaBundle:Documento:tipoDocumento}
#Rutas para institucion
add_institucion:
    path:     /agregar-institucion
    defaults: { _controller: OficialiaBundle:Institucion:addInstitucion }
list_institucion:
    path:   /institucion
    defaults: {_controller: OficialiaBundle:Institucion:listInstitucion }
up_institucion:
    path:   /editar-institucion/{id}
    defaults: {_controller: OficialiaBundle:Institucion:upInstitucion}
del_institucion:
    path:   /elimar-institucion/{id}
    defaults: {_controller: OficialiaBundle:Institucion:delInstitucion }
get_institucion:
    path:   /lista-institucion
    defaults: {_controller: OficialiaBundle:Institucion:getInstitucion }

#Rutas para departamentos
add_departamento:
    path:     /agregar-departamento
    defaults: {_controller: OficialiaBundle:Departamento:addDepartamento }
list_departamento:
    path:    /departamentos
    defaults: {_controller: OficialiaBundle:Departamento:listDepartamentos }
del_departamento:
    path:    /eliminar-departamento/{id}
    defaults: {_controller:OficialiaBundle:Departamento:delDepartamento}
up_departamento:
    path:    /editar-departamento/{id}
    defaults: {_controller: OficialiaBundle:Departamento:upDepartamento}
get_departamento:
    path:   /lista-departamentos
    defaults: {_controller: OficialiaBundle:Departamento:getDepartamentos }


#Rurtas para formatos
add_formato:
    path:     /agregar-formato
    defaults: {_controller: OficialiaBundle:Formato:addFormato }
up_formato:
    path:     /editar-formato/{id}
    defaults: {_controller: OficialiaBundle:Formato:upFormato}
list_formato:
    path:    /formatos
    defaults: {_controller: OficialiaBundle:Formato:listFormato}
del_formato:
    path:   /elimnar-formato/{id}
    defaults: {_controller: OficialiaBundle:Formato:delFormato}
get_formato:
    path:   /lista-formato
    defaults: {_controller: OficialiaBundle:Formato:getFormato}


#Rutas para tipo de documentos 
add_tipoDocumento:
    path:      /agregar-tipo-documento
    defaults: {_controller: OficialiaBundle:TipoDocumento:addTipoDocumento }
list_tipoDocumento:
    path:      /tipo-documento
    defaults: {_controller: OficialiaBundle:TipoDocumento:listTipoDocumento }
up_tipoDocumento:
    path:      /editar-tipo-documento/{id}
    defaults: {_controller: OficialiaBundle:TipoDocumento:upTipoDocumento }
del_tipoDocumento:
    path:      /elimar-tipo-documento/{id}
    defaults: {_controller: OficialiaBundle:TipoDocumento:delTipoDocumento }
get_tipoDocumento:
    path:   /lista-tipo-documento
    defaults: {_controller: OficialiaBundle:TipoDocumento:getTipoDocumento }